"use client";

import { useSearchParams } from "next/navigation";
import { Target } from "@/components/ui/SiteIcons";
import { getTierColor } from "@/lib/tiers";
import type { LeagueFormat } from "@/lib/ddScore";
import {
  PROJECTED_DRAFT_PICK_LIMIT,
  PICKS_PER_ROUND,
  type DraftProjectionResult,
} from "@/lib/draftProjection";

const FORMAT_LABELS: Record<LeagueFormat, string> = {
  "1QB": "1QB · Standard",
  "1QB_TEP": "1QB · TE Premium",
  SUPERFLEX: "Superflex · Standard",
  SUPERFLEX_TEP: "Superflex · TE Premium",
};

function selectedFormatFromParam(value: string | null): LeagueFormat {
  if (value === "1qb") return "1QB";
  if (value === "sf") return "SUPERFLEX";
  if (value === "1qb-tep") return "1QB_TEP";
  if (value === "sf-tep") return "SUPERFLEX_TEP";
  return "SUPERFLEX";
}

function DraftTrack({ projection, color }: { projection: DraftProjectionResult; color: string }) {
  if (!projection.rank || projection.isOutsideDraftableRange) return null;

  const start = Math.max(1, Math.min(PROJECTED_DRAFT_PICK_LIMIT, projection.tierStartRank ?? projection.rank));
  const end = Math.max(start, Math.min(PROJECTED_DRAFT_PICK_LIMIT, projection.tierEndRank ?? projection.rank));
  const point = Math.max(1, Math.min(PROJECTED_DRAFT_PICK_LIMIT, projection.rank));
  const left = ((start - 1) / (PROJECTED_DRAFT_PICK_LIMIT - 1)) * 100;
  const width = Math.max(1.75, ((end - start) / (PROJECTED_DRAFT_PICK_LIMIT - 1)) * 100);
  const pointLeft = ((point - 1) / (PROJECTED_DRAFT_PICK_LIMIT - 1)) * 100;

  return (
    <div className="mt-7">
      <div className="mb-2 flex items-center justify-between gap-4 font-mono text-[9px] uppercase tracking-widest2 text-ink-tertiary">
        <span>Rookie draft board</span>
        <span>12-team · 4 rounds</span>
      </div>
      <div className="relative h-8 border-y border-border-strong/70 bg-surface-raised/60">
        <div className="absolute inset-y-0 left-1/4 border-l border-border/80" />
        <div className="absolute inset-y-0 left-1/2 border-l border-border/80" />
        <div className="absolute inset-y-0 left-3/4 border-l border-border/80" />
        <div
          className="absolute top-1/2 h-2.5 -translate-y-1/2 rounded-full opacity-25"
          style={{ left: `${left}%`, width: `${width}%`, backgroundColor: color }}
        />
        <span
          className="absolute top-1/2 z-10 h-4 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-surface bg-surface shadow-sm"
          style={{ left: `${pointLeft}%`, borderColor: color, boxShadow: `0 0 0 3px color-mix(in srgb, ${color} 14%, transparent)` }}
          aria-label={`Expected pick ${projection.expectedPick}`}
        />
      </div>
      <div className="mt-2 grid grid-cols-4 font-mono text-[9px] uppercase tracking-widest2 text-ink-tertiary">
        {[1, 2, 3, 4].map((round) => (
          <span key={round} className={round === 4 ? "text-right" : ""}>
            {round === 1 ? "Round 1" : round === 4 ? "Round 4" : `Round ${round}`}
          </span>
        ))}
      </div>
    </div>
  );
}

function getProjectionPrecision(windowSize: number) {
  const detail = windowSize === 1 ? "1-pick projection window" : `${windowSize}-pick projection window`;
  if (windowSize <= 2) return { label: "Very tight", detail };
  if (windowSize <= 5) return { label: "Tight", detail };
  if (windowSize <= 10) return { label: "Moderate", detail };
  if (windowSize <= 18) return { label: "Wide", detail };
  return { label: "Very wide", detail };
}

export function DraftProjection({
  projectionsByFormat,
}: {
  projectionsByFormat: Record<LeagueFormat, DraftProjectionResult>;
}) {
  const searchParams = useSearchParams();
  const format = selectedFormatFromParam(searchParams.get("format"));
  const projection = projectionsByFormat[format];
  const color = projection.tier ? getTierColor(projection.tier) : "var(--color-accent)";

  const unavailable = !projection.rank;
  const tierWindow = projection.tierWindowSize ?? 0;
  const projectionPrecision = getProjectionPrecision(Math.max(1, tierWindow));

  return (
    <div className="relative overflow-hidden border border-border-strong bg-surface">
      <div className="pointer-events-none absolute inset-y-0 right-0 hidden w-1/3 bg-grid-columns opacity-30 lg:block" />
      <div className="relative p-6 sm:p-8 lg:p-10">
        <div className="flex flex-wrap items-start justify-between gap-5">
          <div className="flex items-center gap-3">
            <span className="flex h-10 w-10 shrink-0 items-center justify-center border border-accent/35 bg-accent/[0.07] text-accent">
              {/* Use a standard spacing token here. `h-4.5`/`w-4.5` is not
                  generated by this Tailwind setup, which left the SVG without
                  reliable dimensions on mobile. */}
              <Target className="h-5 w-5" strokeWidth={1.75} />
            </span>
            <div>
              <p className="font-mono text-[10px] uppercase tracking-widest2 text-accent">Projected rookie draft</p>
            </div>
          </div>
          <span className="border border-border-strong bg-surface-raised px-3 py-1.5 font-mono text-[9px] uppercase tracking-widest2 text-ink-tertiary">
            {FORMAT_LABELS[format]}
          </span>
        </div>

        {unavailable ? (
          <div className="mt-10 border-t border-border pt-7">
            <p className="font-headline text-3xl uppercase text-ink">Projection unavailable</p>
            <p className="mt-2 max-w-xl text-sm leading-6 text-ink-tertiary">
              This player does not have enough class or score data for a format-aware rookie draft projection yet.
            </p>
          </div>
        ) : (
          <>
            <div className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
              <div>
                <p className="font-mono text-[10px] uppercase tracking-widest2 text-ink-tertiary">Current projection</p>
                <h3 className="mt-2 font-headline text-4xl uppercase leading-none text-ink sm:text-5xl">
                  {projection.label}
                </h3>
                <p className="mt-3 max-w-2xl text-sm leading-6 text-ink-tertiary">
                  Ranked <span className="font-semibold text-ink">#{projection.rank}</span> in this class. The range follows everyone currently inside the same <span className="font-semibold text-ink">{projection.tier}</span> tier, so it expands or contracts as the board changes.
                </p>
              </div>

              <div className="grid min-w-[220px] grid-cols-2 border border-border-strong bg-surface-raised/70">
                <div className="p-4 sm:p-5">
                  <p className="font-mono text-[9px] uppercase tracking-widest2 text-ink-tertiary">Expected</p>
                  <p className="mt-2 font-headline text-3xl text-ink">{projection.expectedPick ?? "—"}</p>
                </div>
                <div className="border-l border-border-strong p-4 sm:p-5">
                  <p className="font-mono text-[9px] uppercase tracking-widest2 text-ink-tertiary">Tier range</p>
                  <p className="mt-2 font-headline text-2xl text-ink" style={{ color }}>{projection.rangeLabel}</p>
                </div>
              </div>
            </div>

            <DraftTrack projection={projection} color={color} />

            <div className="mt-6 grid gap-px border border-border-strong bg-border-strong sm:grid-cols-3">
              <div className="bg-surface px-4 py-3.5">
                <p className="font-mono text-[9px] uppercase tracking-widest2 text-ink-tertiary">Class rank</p>
                <p className="mt-1.5 text-sm font-semibold text-ink">#{projection.rank} of {projection.classSize}</p>
              </div>
              <div className="bg-surface px-4 py-3.5">
                <p className="font-mono text-[9px] uppercase tracking-widest2 text-ink-tertiary">Tier window</p>
                <p className="mt-1.5 text-sm font-semibold text-ink">
                  {tierWindow > 1 ? `${tierWindow} prospects` : "1 prospect"}
                </p>
              </div>
              <div className="bg-surface px-4 py-3.5">
                <p className="font-mono text-[9px] uppercase tracking-widest2 text-ink-tertiary">Projection precision</p>
                <p className="mt-1.5 text-sm font-semibold text-ink">{projectionPrecision.label}</p>
                <p className="mt-0.5 font-mono text-[8px] uppercase tracking-widest2 text-ink-tertiary">{projectionPrecision.detail}</p>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
