/**
 * Name -> School lookup, pulled from the position-specific Class tabs
 * in the Google Sheet (the master data tab that powers live sync doesn't
 * include a School column, so this is a one-time import rather than
 * something that updates automatically like the scores do).
 *
 * Includes every prospect found across the sheet's recruiting tabs,
 * not just ones already in the master graded table -- covers future
 * classes (e.g. 2027/2028) before they're fully graded.
 *
 * Keys are normalized (lowercased, whitespace-collapsed) so small typos
 * in capitalization/spacing between tabs still match correctly.
 */
export const SCHOOL_LOOKUP: Record<string, string> = {
  "a'marion peterson": "UTSA",
  "a.j barner": "MICH",
  "a.j brown": "MISS",
  "a.j derby": "ARK",
  "a.t perry": "WAKE",
  "aaron burbridge": "MSU",
  "aaron hernandez": "FLA",
  "aaron jones": "UTEP",
  "abu sama iii": "WIS",
  "adam mohammed": "CAL",
  "adam randall": "CLEM",
  "adam shaheen": "ASH",
  "adam trautman": "DAYT",
  "adonai mitchell": "TEX",
  "ahmad hardy": "MIZZ",
  "aidan o'connell": "PUR",
  "ainias smith": "TAMU",
  "aj dillon": "BC",
  "albert okwuegbunam": "MIZZ",
  "alec pierce": "CIN",
  "alex collins": "ARK",
  "alex mcgough": "FIU",
  "alexander mattison": "BSU",
  "alize mack": "ND",
  "alvin kamara": "TENN",
  "amara darboh": "MICH",
  "amari cooper": "BAMA",
  "amari rodgers": "CLEM",
  "ameer abdullah": "NEB",
  "amon-ra st. brown": "USC",
  "andre debose": "FLA",
  "andre iosivas": "PRIN",
  "andrew marsh": "MICH",
  "andrew ogletree": "YSU",
  "andy isabella": "UMASS",
  "anthony evans iii": "MISS ST",
  "anthony gould": "ORE ST",
  "anthony mcfarland jr.": "MARY",
  "anthony miller": "MEM",
  "anthony richardson": "FLA",
  "anthony schwartz": "AUB",
  "anthony smith": "ECU",
  "antoine green": "UNC",
  "antonio callaway": "FLA",
  "antonio gandy-golden": "LIB",
  "antonio gibson": "MEM",
  "antonio williams": "CLEM",
  "antwan raymond": "RUT",
  "arch manning": "TEX",
  "ardarius stewart": "BAMA",
  "arian smith": "UGA",
  "ashton bethel-roman": "TAMU",
  "ashton jeanty": "BSU",
  "athan kaliakmanis": "RUT",
  "auden tate": "FSU",
  "audric estime": "ND",
  "austin hooper": "STAN",
  "austin proehl": "UNC",
  "bailey zappe": "WKU",
  "baker mayfield": "OU",
  "barion brown": "LSU",
  "bauer sharp": "LSU",
  "beau sandland": "MON ST",
  "behren morton": "TTU",
  "ben dinucci": "JMU",
  "ben sinnott": "KSU",
  "ben skowronek": "ND",
  "benny snell jr.": "UK",
  "bhayshul tuten": "VA TECH",
  "bijan robinson": "TEX",
  "blake bell": "OU",
  "blake corum": "MICH",
  "bo jackson": "OSU",
  "bo melton": "RUT",
  "bo nix": "ORE",
  "bo scarbrough": "BAMA",
  "boston scott": "LA TECH",
  "brad kaaya": "MIA",
  "braelon allen": "WISC",
  "brandon aiyuk": "ASU",
  "brandon allen": "ARK",
  "brandon doughty": "WKU",
  "branson robinson": "GA ST.",
  "brashard smith": "SMU",
  "braxton berrios": "MIA",
  "braxton miller": "OSU",
  "brayden willis": "OU",
  "braylon staley": "TENN",
  "breece hall": "ISU",
  "brendan rice": "USC",
  "brenen thompson": "MISS ST.",
  "brenton strange": "PSU",
  "breshad perriman": "UCF",
  "brett hundley": "UCLA",
  "brett norfleet": "MIZZ",
  "brevin jordan": "MIA",
  "brian hill": "WYO",
  "brian robinson jr.": "BAMA",
  "brian thomas jr.": "LSU",
  "brittain brown": "UCLA",
  "brock bowers": "UGA",
  "brock purdy": "ISU",
  "bryan edwards": "SC",
  "bryant wesco jr.": "CLEM",
  "bryce lance": "NDSU",
  "bryce love": "STAN",
  "bryce petty": "BAY",
  "bryce underwood": "MICH",
  "bryce young": "BAMA",
  "brycen hopkins": "PUR",
  "bryson washington": "AUB",
  "bub means": "PITT",
  "bucky hodges": "VA TECH",
  "bucky irving": "ORE",
  "bud sasser": "MIZZ",
  "c.j beathard": "IOWA",
  "c.j prosise": "ND",
  "c.j stroud": "OSU",
  "c.j uzomah": "AUB",
  "cade klubnik": "CLEM",
  "cade otton": "WASH",
  "cade stover": "OSU",
  "caleb douglas": "TTU",
  "caleb hawkins": "OK ST",
  "caleb lohner": "UTAH",
  "caleb williams": "USC",
  "caleb wilson": "UCLA",
  "calvin austin": "MEM",
  "calvin ridley": "BAMA",
  "cam akers": "FSU",
  "cam coleman": "TEX",
  "cam cook": "WVU",
  "cam miller": "NDSU",
  "cam skattebo": "ASU",
  "cam ward": "MIA",
  "cameron artis-payne": "AUB",
  "cameron latu": "BAMA",
  "cardale jones": "OSU",
  "carlos henderson": "LTU",
  "carnell tate": "OSU",
  "carsen ryan": "BYU",
  "carson beck": "MIA",
  "carson wentz": "NDSU",
  "casey washington": "ILL",
  "cedric tillman": "TENN",
  "cedrick wilson jr": "BSU",
  "ceedee lamb": "OU",
  "chad hansen": "CAL",
  "chad kelly": "MISS",
  "chad williams": "GRAM ST.",
  "chandler cox": "AUB",
  "charlie becker": "IU",
  "charlie jones": "PUR",
  "charlie kolar": "ISU",
  "charlie woerner": "UGA",
  "charone peake": "CLEM",
  "chase brown": "ILL",
  "chase claypool": "ND",
  "chase edmonds": "FORD",
  "chigoziem okonkwo": "MARY",
  "chimere dike": "FLA",
  "chris bell": "LOU",
  "chris brazzell ii": "TENN",
  "chris carson": "OK ST",
  "chris conley": "UGA",
  "chris evans": "MICH",
  "chris godwin": "PSU",
  "chris herndon": "MIA",
  "chris johnson jr.": "CLEM",
  "chris moore": "CIN",
  "chris oladokun": "SDSU",
  "chris olave": "OSU",
  "chris rodriguez jr.": "KENT",
  "christian bentancur": "CLEM",
  "christian hackenberg": "PSU",
  "christian kirk": "TAMU",
  "christian mccaffrey": "STAN",
  "christian watson": "NDSU",
  "chuba hubbard": "OKST",
  "cj bailey": "NC ST",
  "cj baxter": "UK",
  "cj carr": "ND",
  "cj daniels": "MIA",
  "cj williams": "STAN",
  "clayton thorson": "NW",
  "clayton tune": "HOU",
  "clive walford": "MIA",
  "clyde edwards-helaire": "LSU",
  "cody core": "MISS",
  "cody kessler": "USC",
  "colbie young": "UGA",
  "colby parkinson": "STAN",
  "cole kmet": "ND",
  "cole mcdonald": "HAW",
  "cole payton": "NDSU",
  "cole turner": "NEV",
  "collin johnson": "TEX",
  "colston loveland": "MICH",
  "colton dowell": "UTM",
  "connor cook": "MSU",
  "connor heyward": "MSU",
  "cooper barkate": "MIA",
  "cooper kupp": "EWU",
  "corey coleman": "BAY",
  "corey davis": "WMU",
  "corey smith": "TOL",
  "cornelius johnson": "MICH",
  "cornell powell": "CLEM",
  "courtland sutton": "SMU",
  "curtis samuel": "OSU",
  "cyrus allen": "CIN",
  "d'andre swift": "UGA",
  "d'onta foreman": "TEX",
  "d'wayne eskridge": "WMU",
  "d.j chark": "LSU",
  "d.j moore": "MARY",
  "d.k metcalf": "MISS",
  "da'ron brown": "NIU",
  "daesean hamilton": "PSU",
  "dak prescott": "MISS ST",
  "dakorien moore": "ORE",
  "dallas goedert": "SDSU",
  "dallen bentley": "UTAH",
  "dalton keene": "VA TECH",
  "dalton kincaid": "UTAH",
  "dalton schultz": "STAN",
  "dalvin cook": "FSU",
  "dameon pierce": "FLA",
  "damien harris": "BAMA",
  "damien martinez": "MIA",
  "damion ratley": "TAMU",
  "daniel bellinger": "SDSU",
  "daniel braverman": "WMU",
  "daniel jones": "DUKE",
  "daniel lasco": "CAL",
  "danny etling": "LSU",
  "danny gray": "SMU",
  "dante dowdell": "UGA",
  "dante moore": "ORE",
  "dante pettis": "WASH",
  "dareke young": "LRU",
  "darian mensah": "MIA",
  "darius jackson": "EMU",
  "darius slayton": "AUB",
  "darius taylor": "MINN",
  "darnell mooney": "TUL",
  "darnell washington": "UGA",
  "darrell henderson": "MEM",
  "darren waller": "GA TECH",
  "darrynton evans": "APP ST",
  "darwin thompson": "USU",
  "daurice fountain": "N IOWA",
  "david bell": "PUR",
  "david cobb": "MINN",
  "david johnson": "N IOWA",
  "david mills": "STAN",
  "david montgomery": "ISU",
  "david moore": "EC OK",
  "david morgan": "UTSA",
  "david njoku": "MIA",
  "david williams": "ARK",
  "davis allen": "CLEM",
  "davis webb": "CAL",
  "dawson knox": "MISS",
  "dax milne": "BYU",
  "dazz newsome": "UNC",
  "de'angelo henderson": "CC",
  "de'zhaun stribling": "MISS",
  "deandre moore": "COL",
  "deandre smelter": "GA TECH",
  "deandre washington": "TTU",
  "deangelo yancey": "PUR",
  "dede westbrook": "OU",
  "deebo samuel": "SC",
  "deejay dallas": "MIA",
  "deion burks": "OU",
  "demarcus ayers": "HOU",
  "demarcus robinson": "FLA",
  "demario douglas": "LIB",
  "demond claiborne": "WF",
  "denzel boston": "WASH",
  "denzel mims": "BAY",
  "deon cain": "CLEM",
  "derius davis": "TCU",
  "derrick henry": "BAMA",
  "derrius guice": "LSU",
  "desean bishop": "TENN",
  "deshaun watson": "CLEM",
  "deshone kizer": "ND",
  "desmond ridder": "CIN",
  "deuce vaughn": "KSU",
  "devante mays": "USU",
  "devante parker": "LOU",
  "devaughn vele": "UTAH",
  "devin asiasi": "UCLA",
  "devin culp": "WASH",
  "devin duvernay": "TEX",
  "devin fuller": "UCLA",
  "devin funchess": "MICH",
  "devin leary": "UK",
  "devin lucien": "ASU",
  "devin neal": "KAN",
  "devin singletary": "FAU",
  "devin smith": "OSU",
  "devon achane": "TAMU",
  "devonta smith": "BAMA",
  "devontae booker": "UTAH",
  "devontez walker": "UNC",
  "dewayne mcbride": "UAB",
  "dexter williams": "ND",
  "dez fitzpatrick": "LOU",
  "dezmin lewis": "C ARK",
  "dezmon patmon": "WSU",
  "dillon gabriel": "ORE",
  "dillon mitchell": "ORE",
  "diontae johnson": "TOL",
  "dj giddens": "KSU",
  "dj lagway": "BAY",
  "dominic lovett": "UGA",
  "donnel pumphrey": "SDSU",
  "donovan peoples-jones": "MICH",
  "dont'e thornton jr.": "TEN",
  "dontayvion wicks": "UVA",
  "dorial green-beckham": "MIZZ",
  "dorian thompson-robinson": "UCLA",
  "drake lindsey": "MINN",
  "drake london": "USC",
  "drake maye": "UNC",
  "drew allar": "PSU",
  "drew lock": "MIZZ",
  "drew mestemaker": "OK ST",
  "drew sample": "WASH",
  "duce robinson": "FSU",
  "duke johnson": "MIA",
  "durham smythe": "ND",
  "dwayne haskins": "OSU",
  "dwayne washington": "WAS",
  "dyami brown": "UNC",
  "dylan cantrell": "TTU",
  "dylan edwards": "KAN",
  "dylan laube": "NHU",
  "dylan raiola": "ORE",
  "dylan riley": "BSU",
  "dylan sampson": "TENN",
  "easton stick": "NDSU",
  "eli heidenreich": "NAVY",
  "eli raridon": "ND",
  "eli stowers": "VAN",
  "elic ayomanor": "STAN",
  "elijah arroyo": "MIA",
  "elijah higgins": "STAN",
  "elijah hood": "UNC",
  "elijah mcguire": "UL",
  "elijah mitchell": "UL",
  "elijah moore": "MISS",
  "elijah sarratt": "IU",
  "emeka egbuka": "OSU",
  "emmanuel henderson": "KAN",
  "emmett johnson": "NEB",
  "eno benjamin": "ASU",
  "equanimeous st. brown": "ND",
  "eric gray": "OU",
  "eric saubert": "DRAKE",
  "eric singleton jr.": "FLA",
  "erick all": "IOWA",
  "eriz ezukanma": "TTU",
  "eugene wilson iii": "LSU",
  "evan engram": "MISS",
  "evan hull": "NW",
  "evan pryor": "FLA",
  "evan spencer": "OSU",
  "evan stewart": "ORE",
  "ezekiel elliott": "OSU",
  "fernando mendoza": "IU",
  "fluff bothwell": "MISS ST",
  "foster moreau": "LSU",
  "frank darby": "ASU",
  "freddie swain": "FLA",
  "gabriel davis": "UCF",
  "gardner minshew ii": "WSU",
  "garrett grayson": "CSU",
  "garrett nussmeier": "LSU",
  "garrett wilson": "OSU",
  "gary brightwell": "ARI",
  "gary jennings jr.": "WVU",
  "gavin bartholomew": "PITT",
  "gavin hoffman": "IOWA",
  "gavin sawchuk": "NW",
  "geoff swaim": "TEX",
  "george kittle": "IOWA",
  "george pickens": "UGA",
  "gerald christian": "LOU",
  "gerald everett": "S BAMA",
  "geremy davis": "UCONN",
  "germie bernard": "BAMA",
  "gerrid doaks": "CIN",
  "graham mertz": "FLA",
  "grant calcaterra": "SMU",
  "grant dubose": "CHAR",
  "grant stec": "WIS",
  "greg dulcich": "UCLA",
  "griffin wilde": "NW",
  "gunnar helm": "TEX",
  "hakeem butler": "ISU",
  "harold fannin jr.": "BGSU",
  "harrison bryant": "FAU",
  "hassan haskins": "MICH",
  "hayden hurst": "SC",
  "hendon hooker": "TENN",
  "henry ruggs iii": "BAMA",
  "hogan hansen": "MICH",
  "hollywood brown": "OU",
  "hollywood smothers": "TEX",
  "hunter henry": "ARK",
  "hunter long": "BC",
  "hunter renfrow": "CLEM",
  "ian book": "ND",
  "ian strong": "CAL",
  "ian thomas": "IU",
  "ihmir smith-marsette": "IOWA",
  "irv smith jr.": "BAMA",
  "isaac brown": "LOU",
  "isaac nauta": "UGA",
  "isaac teslaa": "ARK",
  "isaiah augustave": "SC",
  "isaiah coulter": "RIU",
  "isaiah davis": "SDSU",
  "isaiah ford": "VA TECH",
  "isaiah hodgins": "ORE ST",
  "isaiah horton": "TAMU",
  "isaiah likely": "CC",
  "isaiah mckenzie": "UGA",
  "isaiah spiller": "TAMU",
  "isiah pacheco": "RUT",
  "israel abanikanda": "PITT",
  "issac guerendo": "LOU",
  "ito smith": "SO MISS",
  "j'koby williams": "TTU",
  "j'mon moore": "MIZZ",
  "j.j arcega-whiteside": "STAN",
  "j.j. mccarthy": "MICH",
  "j.k dobbins": "OSU",
  "ja'kobi lane": "USC",
  "ja'lynn polk": "WASH",
  "ja'marr chase": "LSU",
  "ja'tavion sanders": "TEX",
  "jace sternberger": "TAMU",
  "jack bech": "TCU",
  "jack endries": "TEX",
  "jackson hawes": "GA TECH",
  "jacob cowing": "ARI",
  "jacob eason": "WAS",
  "jacob harris": "UCF",
  "jacoby brissett": "NC ST",
  "jacory croskey-merritt": "ARI",
  "jadan baugh": "FLA",
  "jadarian price": "ND",
  "jaden bray": "WVU",
  "jaden greathouse": "ND",
  "jaden reddell": "UGA",
  "jaelen strong": "ASU",
  "jaelon darden": "N TEX",
  "jahan dotson": "PSU",
  "jaheim bell": "FSU",
  "jahiem white": "UNT",
  "jahmyr gibbs": "BAMA",
  "jake butt": "MICH",
  "jake ferguson": "WIS",
  "jake fromm": "UGA",
  "jake funk": "MARY",
  "jake haener": "FRES ST",
  "jake luton": "ORE ST",
  "jake rudock": "MICH",
  "jakeem grant": "TTU",
  "jaleel scott": "NM ST",
  "jalen brooks": "SC",
  "jalen camp": "GA TECH",
  "jalen hurd": "BAY",
  "jalen hurts": "OU",
  "jalen mcmillan": "WASH",
  "jalen milroe": "BAMA",
  "jalen nailor": "MSU",
  "jalen reagor": "TCU",
  "jalen royals": "USU",
  "jalen tolbert": "S BAMA",
  "jalin hyatt": "TENN",
  "jam miller": "BAMA",
  "jamaal williams": "BYU",
  "jamari johnson": "ORE",
  "jamari thrash": "LOU",
  "jameis winston": "FSU",
  "james conner": "PITT",
  "james cook": "UGA",
  "james mitchell": "VA TECH",
  "james morgan": "FIU",
  "james o'shaughnessy": "ILL ST",
  "james peoples": "PSU",
  "james proche": "SMU",
  "james washington": "OK ST",
  "jameson williams": "BAMA",
  "jamie tremble": "CUSE",
  "jamison crowder": "DUKE",
  "jared goff": "CAL",
  "jared wiley": "TCU",
  "jaren hall": "BYU",
  "jaren kanak": "OU",
  "jaron-keawe sagapolutele": "CAL",
  "jarquez hunter": "AUB",
  "jarrett stidham": "AUB",
  "jase mcclellan": "BAMA",
  "jason huntley": "NM ST",
  "jauan jennings": "TENN",
  "javon baker": "UCF",
  "javonte williams": "UNC",
  "javorius allen": "USC",
  "jawhar jordan": "LOU",
  "jaxon smith-njigba": "OSU",
  "jaxson dart": "MISS",
  "jay ajayi": "BSU",
  "jayce brown": "LSU",
  "jayden daniels": "LSU",
  "jayden higgins": "ISU",
  "jayden maiava": "USC",
  "jayden reed": "MSU",
  "jaydon blue": "TEX",
  "jaylen samuels": "NC ST",
  "jaylen waddle": "BAMA",
  "jaylen wright": "TENN",
  "jaylin lane": "VA TECH",
  "jaylin noel": "ISU",
  "jeff driskel": "LA TECH",
  "jeff heuerman": "OSU",
  "jehu chesson": "MICH",
  "jelani woods": "UVA",
  "jerell adams": "SC",
  "jeremiah cobb": "AUB",
  "jeremiah smith": "OSU",
  "jeremiyah love": "ND",
  "jeremy langford": "MSU",
  "jeremy mcnichols": "BSU",
  "jeremy payne": "TCU",
  "jeremy ruckert": "OSU",
  "jeremy sprinkle": "ARK",
  "jermaine burton": "BAMA",
  "jermar jefferson": "ORE ST",
  "jerome ford": "CIN",
  "jerry jeudy": "BAMA",
  "jesse james": "PSU",
  "jha'quan jackson": "TUL",
  "jimmy horn jr.": "COL",
  "jj nelson": "UAB",
  "joe burrow": "LSU",
  "joe milton": "TENN",
  "joe mixon": "OU",
  "joe reed": "UVA",
  "joe royer": "CIN",
  "joe williams": "UTAH",
  "john bates": "BSU",
  "john fitzpatrick": "UGA",
  "john hightower": "BSU",
  "john kelly": "TENN",
  "john mateer": "OU",
  "john metchie": "BAMA",
  "john ross": "WASH",
  "john ursua": "HAW",
  "johnny wilson": "FSU",
  "johntay cook": "MISS",
  "jonah coleman": "WASH",
  "jonathan williams": "ARK",
  "jonathon brooks": "TEX",
  "jonathon mingo": "MISS",
  "jonathon taylor": "WIS",
  "jonnu smith": "FIU",
  "jordan addison": "USC",
  "jordan akins": "UCF",
  "jordan howard": "IU",
  "jordan james": "ORE",
  "jordan lasley": "UCLA",
  "jordan leggett": "CLEM",
  "jordan love": "UTAH ST",
  "jordan marshall": "MICH",
  "jordan payton": "UCLA",
  "jordan scarlett": "FLA",
  "jordan thomas": "MISS ST",
  "jordan travis": "FSU",
  "jordan whittington": "TEX",
  "jordan wilkins": "MISS",
  "jordyn tyson": "ASU",
  "josh allen": "WYO",
  "josh cameron": "BAY",
  "josh cuevas": "BAMA",
  "josh doctson": "TCU",
  "josh downs": "UNC",
  "josh jacobs": "BAMA",
  "josh malone": "TENN",
  "josh oliver": "SJSU",
  "josh palmer": "TENN",
  "josh reynolds": "TAMU",
  "josh robinson": "MISS ST",
  "josh rosen": "UCLA",
  "josh whyle": "CIN",
  "joshua dobbs": "TENN",
  "joshua kelley": "UCLA",
  "josiah deguara": "CIN",
  "juju smith-schuster": "USC",
  "julian sayin": "OSU",
  "junior bergen": "MON",
  "junior sherrill": "VANDY",
  "justice haynes": "GA TECH",
  "justice hill": "OK ST",
  "justin fields": "OSU",
  "justin hardy": "ECU",
  "justin herbert": "ORE",
  "justin jackson": "NW",
  "justin jefferson": "LSU",
  "justin joly": "NC ST",
  "justin shorter": "FLA",
  "justin watson": "PENN",
  "juwann winfree": "COL",
  "k.j. hill": "OSU",
  "k.j. osborn": "MIA",
  "kadarius toney": "FLA",
  "kaden prather": "MARY",
  "kaden smith": "STAN",
  "kaden wetjen": "IOWA",
  "kaelin clay": "UTAH",
  "kaelon black": "IU",
  "kahale warring": "SDSU",
  "kaleb johnson": "IOWA",
  "kalel mullings": "MICH",
  "kalen ballage": "ASU",
  "kanye udoh": "LIB",
  "kareem hunt": "TOL",
  "karlos williams": "FSU",
  "kawaan baker": "S BAMA",
  "kayshon boutte": "LSU",
  "kaytron allen": "PSU",
  "kc concepcion": "TAMU",
  "ke'shawn vaughn": "VAN",
  "keandre lambert-smith": "AUB",
  "keaontay ingram": "USC",
  "keenan reynolds": "NAVY",
  "keesean johnson": "FRES ST",
  "keilan robinson": "TEX",
  "keith marshall": "UGA",
  "keith mumphery": "MSU",
  "keke coutee": "TTU",
  "kellen mond": "TAMU",
  "kelvin harmon": "NC ST",
  "kelvin taylor": "FLA",
  "kendre miller": "TCU",
  "kendrick law": "UK",
  "kene nwangwu": "ISU",
  "kennard backman": "UAB",
  "kenneth dixon": "LA TECH",
  "kenneth gainwell": "MEM",
  "kenneth walker iii": "MSU",
  "kenny bell": "NEB",
  "kenny golladay": "NIU",
  "kenny hilliard": "LSU",
  "kenny lawler": "CAL",
  "kenny mcintosh": "UGA",
  "kenny pickett": "PITT",
  "kenyan drake": "BAMA",
  "kenyon sadiq": "ORE",
  "keon coleman": "FSU",
  "kerrith whyte jr.": "FAU",
  "kerryon johnson": "AUB",
  "kevin coleman jr.": "MIZZ",
  "kevin harris": "SC",
  "kevin hogan": "STAN",
  "kevin white": "WV",
  "kewan lacy": "MISS",
  "keyjuan brown": "LOU",
  "khalfani muhammad": "CAL",
  "khalil herbert": "VA TECH",
  "khalil shakir": "BSU",
  "kimani vidal": "TROY",
  "kj duff": "RUT",
  "kj hamler": "PSU",
  "ko kieft": "MINN",
  "kolby listenbee": "TCU",
  "konata mumpfield": "PITT",
  "kurtis rourke": "IU",
  "kyle lauletta": "RICH",
  "kyle mccord": "CUSE",
  "kyle monangai": "RUT",
  "kyle phillips": "UCLA",
  "kyle pitts": "FLA",
  "kyle trask": "FLA",
  "kyle williams": "WSU",
  "kylen granson": "SMU",
  "kyler murray": "OU",
  "kylin hill": "MISS ST",
  "kyren williams": "ND",
  "la'mical perine": "FLA",
  "ladd mcconkey": "UGA",
  "lajohntay wester": "COL",
  "lamar jackson": "LOU",
  "lanorris sellers": "SC",
  "laquon treadwell": "MISS",
  "larry rountree iii": "MIZZ",
  "laviska shenault jr.": "COL",
  "leonard fournette": "LSU",
  "leonte carroo": "RUT",
  "lequint allen": "CUSE",
  "lew nichols": "CMU",
  "lewis bond": "BC",
  "lj martin": "BYU",
  "logan woodside": "TOL",
  "london humphreys": "UGA",
  "luke falk": "WSU",
  "luke farrell": "OSU",
  "luke lachey": "IOWA",
  "luke mccaffrey": "RICE",
  "luke musgrave": "ORE ST",
  "luke reynolds": "VA TECH",
  "luke schoonmaker": "MICH",
  "luther burden": "MIZZ",
  "lynn bowden jr.": "UK",
  "mac jones": "BAMA",
  "mack hollins": "UNC",
  "makai lemon": "USC",
  "makhi hughes": "HOU",
  "malachi corley": "WKU",
  "malachi dupre": "LSU",
  "malachi fields": "ND",
  "malachi toney": "MIA",
  "malcolm johnson": "MISS ST",
  "malcolm mitchell": "UGA",
  "malcolm perry": "NAVY",
  "malik benson": "ORE",
  "malik nabers": "LSU",
  "malik washington": "UVA",
  "malik willis": "LIB",
  "marcell ateman": "OK ST",
  "marcus green": "ULM",
  "marcus mariota": "ORE",
  "marcus murphy": "MIZZ",
  "mario alford": "WV",
  "mario craver": "TAMU",
  "mark andrews": "OU",
  "mark fletcher jr.": "MIA",
  "mark walton": "MIA",
  "marlin klein": "MICH",
  "marlon mack": "USF",
  "marquez stevenson": "HOU",
  "marquez valdez-scantling": "USF",
  "marshawn lloyd": "USC",
  "marvin harrison jr.": "OSU",
  "marvin mims": "OU",
  "mason rudolph": "OK ST",
  "mason schrek": "BUF",
  "mason taylor": "LSU",
  "matt corral": "MISS",
  "matt jones": "FLA",
  "matthew dayes": "NC ST",
  "matthew golden": "TEX",
  "matthew hibner": "SMU",
  "max bredeson": "MICH",
  "max duggan": "TCU",
  "max klare": "OSU",
  "maxx williams": "MINN",
  "mecole hardman": "UGA",
  "melvin gordon": "WIS",
  "michael carter": "UNC",
  "michael gallup": "CSU",
  "michael mayer": "ND",
  "michael penix": "WASH",
  "michael pittman jr.": "USC",
  "michael pratt": "TUL",
  "michael roberts": "TOL",
  "michael thomas": "OSU",
  "michael wilson": "STAN",
  "michael woods ii": "OU",
  "mike davis": "SC",
  "mike gesicki": "PSU",
  "mike matthews": "TENN",
  "mike strachan": "CHAR",
  "mike thomas": "SO MISS",
  "mike washington jr.": "ARK",
  "mike weber": "OSU",
  "mike white": "WKU",
  "mike williams": "CLEM",
  "miles boykin": "ND",
  "miles sanders": "PSU",
  "mitchell evans": "ND",
  "mitchell trubisky": "UNC",
  "moliki matavao": "UCLA",
  "montrell washington": "SAM",
  "moritz boehringer": "GERMANY",
  "mycole pruitt": "S ILL",
  "myles gaskin": "WASH",
  "n'keal harry": "ASU",
  "najee harris": "BAMA",
  "nate boerkircher": "TAMU",
  "nate frazier": "UGA",
  "nate sheppard": "DUKE",
  "nate stanley": "IOWA",
  "nate sudfeld": "IU",
  "nathan peterman": "PITT",
  "neal sterling": "MONM",
  "nelson agholor": "USC",
  "nic anderson": "UK",
  "nicholas singleton": "PSU",
  "nick bawden": "SDSU",
  "nick boyle": "DEL",
  "nick chubb": "UGA",
  "nick marsh": "IU",
  "nick muse": "SC",
  "nick o'leary": "FSU",
  "nick vannett": "OSU",
  "nico collins": "MICH",
  "nico iamaleava": "UCLA",
  "noah brown": "OSU",
  "noah fant": "IOWA",
  "noah gray": "DUKE",
  "nyck harbor": "SC",
  "nyheim hines": "NC ST",
  "nyziah hunter": "NEB",
  "o.j howard": "BAMA",
  "olabisi johnson": "CSU",
  "ollie gordon": "OKST",
  "omar cooper jr.": "IU",
  "omarion hampton": "UNC",
  "omarion miller": "ASU",
  "oronde gadsden ii": "CUSE",
  "oscar delp": "UGA",
  "parker washington": "PSU",
  "parris campbell": "OSU",
  "pat bryant": "ILL",
  "pat freiermuth": "PSU",
  "patrick mahomes": "TTU",
  "paul perkins": "UCLA",
  "paxton lynch": "MEM",
  "payne durham": "PUR",
  "pharoh cooper": "SC",
  "phil mafah": "CLEM",
  "phillip dorsett": "MIA",
  "pierre strong": "SDSU",
  "puka nacua": "BYU",
  "qadree ollison": "PITT",
  "quentin johnston": "TCU",
  "quez watkins": "S MISS",
  "quinn ewers": "TEX",
  "quinshon judkins": "OSU",
  "quintez cephus": "WIS",
  "quinton joyner": "TTU",
  "quintrevion wisner": "FSU",
  "racey mcmath": "LSU",
  "rachaad white": "ASU",
  "raleek brown": "TEX",
  "randall telfer": "USC",
  "rashad greene": "FSU",
  "rashad penny": "SDSU",
  "rashard higgins": "CSU",
  "rashee rice": "SMU",
  "rasheen ali": "MARSH",
  "rashod bateman": "MINN",
  "ray davis": "KENT",
  "ray-ray mccloud": "CLEM",
  "raymond calais": "UL",
  "rayshon luke": "FRES ST.",
  "reggie virgil": "TTU",
  "rhamondre stevenson": "OU",
  "ricardo louis": "AUB",
  "richie james": "MTSU",
  "ricky pearsall": "FLA",
  "ricky white iii": "UNLV",
  "rico gathers": "BAY",
  "riley leonard": "ND",
  "riley nowakowski": "IU",
  "riley ridley": "UGA",
  "rj harvey": "UCF",
  "rob gronkowski": "ARI",
  "robbie ouzts": "BAMA",
  "robert davis": "GA ST.",
  "roderick robinson": "UAB",
  "rodney adams": "USF",
  "rodney anderson": "OU",
  "roman wilson": "MICH",
  "rome odunze": "WASH",
  "romeo doubs": "NEV",
  "ronald jones ii": "USC",
  "rondale moore": "PUR",
  "ronnie bell": "MICH",
  "rory anderson": "SC",
  "roschon johnson": "TEX",
  "royce freeman": "ORE",
  "russell gage": "LSU",
  "ryan finley": "NC ST",
  "ryan flournoy": "SEMO",
  "ryan izzo": "FSU",
  "ryan switzer": "UNC",
  "ryan williams": "BAMA",
  "ryan wingo": "TEX",
  "ryquell armstead": "TEM",
  "sam darnold": "USC",
  "sam ehlinger": "TEX",
  "sam howell": "UNC",
  "sam laporta": "IOWA",
  "sam leavitt": "ASU",
  "sam roush": "STAN",
  "samaje perine": "OU",
  "sammie coates": "AUB",
  "samori toure": "NEB",
  "saquon barkley": "PSU",
  "savion williams": "TCU",
  "scott miller": "BGSU",
  "sean clifford": "PSU",
  "sean mannion": "ORE ST",
  "seth devalve": "PRIN",
  "seth mcgowan": "UK",
  "seth williams": "AUB",
  "seydou traore": "MISS ST",
  "shedeur sanders": "COL",
  "shelton gibson": "WVU",
  "shi smith": "SC",
  "simi fehoko": "STAN",
  "skylar thompson": "KSU",
  "skyler bell": "UCONN",
  "skyy moore": "WMU",
  "snoop conner": "MISS",
  "sony michel": "UGA",
  "spencer rattler": "SC",
  "stacy coley": "MIA",
  "stefon diggs": "MARY",
  "stephen sullivan": "LSU",
  "sterling shepard": "OU",
  "stetson bennett": "UGA",
  "t.j hockenson": "IOWA",
  "t.j logan": "UNC",
  "t.j moore": "CLEM",
  "t.j. yeldon": "BAMA",
  "tahj brooks": "TTU",
  "tahj washington": "USC",
  "tai felton": "MARY",
  "tajae sharpe": "UMASS",
  "tank bigsby": "AUB",
  "tank dell": "HOU",
  "tanner koziol": "HOU",
  "tanner lee": "NEB",
  "tanner mckee": "STAN",
  "tanner mclachlan": "ARI",
  "taylen green": "ARK",
  "taywan taylor": "WKU",
  "teagan quitoriano": "ORE ST",
  "ted hurst": "GA ST.",
  "tee higgins": "CLEM",
  "tehjaun palmer": "UAB",
  "temarrick hemingway": "SC ST",
  "terrace marshall jr.": "LSU",
  "terrance carter": "TTU",
  "terrance ferguson": "ORE",
  "terry godwin": "UGA",
  "terry mclaurin": "OSU",
  "tetairoa mcmillan": "ARI",
  "tevin coleman": "IU",
  "tez johnson": "ORE",
  "theo johnson": "PSU",
  "thomas duarte": "UCLA",
  "thomas fidone ii": "NEB",
  "tip reiman": "ILL",
  "todd gurley": "UGA",
  "tommy mellott": "MON ST",
  "tommy stevens": "MISS ST",
  "tommy sweeney": "BC",
  "tommy tremble": "ND",
  "tony pollard": "MEM",
  "tory horton": "CSU",
  "trace mcsorley": "PSU",
  "travis etienne": "CLEM",
  "travis fulgham": "ODU",
  "travis homer": "MIA",
  "travis hunter": "COL",
  "travis kelce": "CIN",
  "trayveon williams": "VAN",
  "tre harris": "MISS",
  "tre mcbride": "W\\&M",
  "tre nixon": "UCF",
  "tre richardson": "LOU",
  "tre tucker": "CIN",
  "tre' mckitty": "UGA",
  "tre'quan smith": "UCF",
  "trent taylor": "LA TECH",
  "trent walker": "HOU",
  "trenton cannon": "VA ST",
  "trestan ebner": "BAY",
  "treveyon henderson": "OSU",
  "trevon wesco": "WVU",
  "trevor davis": "CAL",
  "trevor etienne": "UGA",
  "trevor lawrence": "CLEM",
  "trevor siemian": "NW",
  "trey benson": "FSU",
  "trey holly": "SOU",
  "trey lance": "NDSU",
  "trey mcbride": "CSU",
  "trey palmer": "NEB",
  "trey quinn": "SMU",
  "trey sermon": "OSU",
  "trey'dez green": "LSU",
  "treylon burks": "ARK",
  "trinidad chambliss": "MISS",
  "troy franklin": "ORE",
  "troy fumagalli": "WIS",
  "tua tagovailoa": "BAMA",
  "tucker kraft": "SDSU",
  "tutu atwell": "LOU",
  "ty chandler": "UNC",
  "ty johnson": "MARY",
  "ty montgomery": "STAN",
  "ty simpson": "BAMA",
  "tyjae spears": "TUL",
  "tylan wallace": "OK ST",
  "tyler allgeier": "BYU",
  "tyler badie": "MIZZ",
  "tyler boyd": "PITT",
  "tyler conklin": "CMU",
  "tyler davis": "GA TECH",
  "tyler ervin": "SJSU",
  "tyler higbee": "WKU",
  "tyler johnson": "MINN",
  "tyler kroft": "RUT",
  "tyler lockett": "KSU",
  "tyler scott": "CIN",
  "tyler shough": "LOU",
  "tyler warren": "PSU",
  "tyquan thornton": "BAY",
  "tyreek hill": "W. BAMA",
  "tyrie cleveland": "FLA",
  "tyrion davis-price": "LSU",
  "tyrone tracy jr.": "PUR",
  "van jefferson": "FLA",
  "velus jones": "TENN",
  "vince mayle": "WSU",
  "wan'dale robinson": "UK",
  "waymond jordan": "USC",
  "wayne gallman": "CLEM",
  "wayshawn parker": "UTAH",
  "wendell smallwood": "WVU",
  "will dissly": "WASH",
  "will fuller": "ND",
  "will grier": "WVU",
  "will howard": "OSU",
  "will kacmarek": "OSU",
  "will levis": "UK",
  "will mallory": "MIA",
  "will shipley": "CLEM",
  "woody marks": "USC",
  "wyatt young": "OK ST",
  "xavier hutchinson": "ISU",
  "xavier legette": "SC",
  "xavier worthy": "TEX",
  "zac brooks": "CLEM",
  "zach charbonnet": "UCLA",
  "zach davidson": "C MIZZ ST",
  "zach ertz": "STAN",
  "zach evans": "MISS",
  "zach gentry": "MICH",
  "zach wilson": "BYU",
  "zachariah branch": "UGA",
  "zack kuntz": "ODU",
  "zack moss": "UTAH",
  "zamir white": "UGA",
  "zander horvath": "PUR",
  "zavion thomas": "LSU",
  "zay flowers": "BC",
  "zay jones": "ECU",
};

/** Normalize a name the same way the lookup keys are normalized. */
export function normalizeName(name: string): string {
  return name.trim().replace(/\s+/g, " ").toLowerCase();
}

/**
 * A looser normalizer used only to join the master table's Name column
 * against a position tab's Name column — two live, independently-typed
 * columns in the same sheet that don't always agree on punctuation
 * ("A.J. Brown" vs "AJ Brown", curly vs straight apostrophes, hyphens
 * vs spaces). Used on BOTH sides of that join, so it's safe to be more
 * aggressive here than normalizeName(), which has to stay byte-for-byte
 * compatible with the hand-typed SCHOOL_LOOKUP keys above.
 */
export function normalizeNameLoose(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "") // strip accents/diacritics
    .toLowerCase()
    .replace(/['’‘".]/g, "") // drop apostrophes and periods entirely
    .replace(/-/g, " ") // treat hyphens as word separators
    .replace(/\s+/g, " ")
    .trim();
}
